### ISSUE TITLE
Crashing on import of QIF

### ISSUE THREAD

**Issue by shawn1thompson** [cjfloss/envelope#57]
I'm trying to import a qif file from my credit union and the app crashes with no error and nothing imported when reopened.

Thank you.

**Comment by jalenheidelburg** [comment]
I am having the same issue. Also is it possible to add other options of importing such as .qfx or .csv files?

**Comment by cjfloss** [comment]
What is the structure of your .qif file?
For example, the tests are done using
```
    !Type:Bank
    D1/1/2014
    T1500
    PPaycheck
    LIncome.Salary
    ^
    D2/1/2014
    T1500
    PPaycheck
    LIncome.Salary
    ^
```
```
    Account
    Transaction date
    Total amount
    Payee
    Category
```

**Comment by shawn1thompson** [comment]
Looks like mine is:

Date
Description
Amount
Fee
Account Balance

I also have the option to download as CSV or Quicken format if that helps.

**Comment by Ossada** [comment]
I too exiperienced crash upon importing qif file and tried to build the app so that I can debug it a bit more. This is what I get in the terminal when launching the app and clicking on import:

[INFO 15:08:24.623109] Envelope.vala:58: Revision: git-master-0c0b212
[INFO 15:08:24.623161] Envelope.vala:59: Report any issues/bugs you might find to https://github.com/cjfloss/envelope
[INFO 15:08:24.624630] DatabaseManager.vala:540: DATABASE_USER_VERSION: 0
[FATAL 15:08:24.629401] [Gtk] gtk_widget_set_tooltip_text: assertion 'GTK_IS_WIDGET (widget)' failed
[FATAL 15:08:24.629623] [Gtk] gtk_widget_set_tooltip_text: assertion 'GTK_IS_WIDGET (widget)' failed

(com.github.cjfloss.envelope:14359): Gtk-WARNING **: 15:08:24.654: Theme parsing error: <data>:8:38: Using Pango syntax for the font: style property is deprecated; please use CSS syntax
[WARNING 15:08:24.654728] Utils.vala:372: Could not create CSS Provider: <data>:8:26not a numberStylesheet:                EnvelopeViewBudgetOverview {                    background-color: @base_color;                }                EnvelopeViewBudgetOverview GtkLabel {                    color: @placeholder_text_color;                    font: open sans 11;                    text-shadow: none;                }                EnvelopeViewBudgetOverview .h1,                EnvelopeViewBudgetOverview .h3 {                    color: alpha (@text_color, 0.4);                }        

(com.github.cjfloss.envelope:14359): Gtk-WARNING **: 15:08:26.406: Invalid input string

(com.github.cjfloss.envelope:14359): Gtk-WARNING **: 15:08:26.406: Invalid input string

(com.github.cjfloss.envelope:14359): Gtk-WARNING **: 15:08:26.406: Invalid input string

(com.github.cjfloss.envelope:14359): Gtk-WARNING **: 15:08:26.406: Invalid input string

(com.github.cjfloss.envelope:14359): Gtk-WARNING **: 15:08:26.406: Invalid input string

(com.github.cjfloss.envelope:14359): Gtk-WARNING **: 15:08:26.407: Invalid input string

(com.github.cjfloss.envelope:14359): Gtk-WARNING **: 15:08:26.407: Invalid input string

(com.github.cjfloss.envelope:14359): Gtk-WARNING **: 15:08:26.407: Invalid input string

(com.github.cjfloss.envelope:14359): Gtk-WARNING **: 15:08:26.407: Invalid input string

(com.github.cjfloss.envelope:14359): Gtk-WARNING **: 15:08:26.407: Invalid input string
**[FATAL 15:08:31.552949] string_strip: assertion 'self != NULL' failed
Segmentation fault**

Last two lines happen when I select file and click import. Unfortunately, I don't know vala enough to debug further. 
My qif file has the following structure:

!Type:Bank
D31.07.2020
T-1.07
MNadomestilo za uporabo Banke IN
PBanka Intesa Sanpaolo d.d.
^

with a newline separating entries. It also contains special characters (čšž), but I don't think that is the reason for the crash, since I manually swapped them all out to test this. Hope this helps.

**Comment by shawn1thompson** [comment]
No longer using Envelope or Elementary unfortunately.
